- name: Rollback to previous commit
  hosts: all
  become: true

  vars:
    deploy_path: /www/wwwroot/n8n.atharvadevasthali.com

  tasks:
    - name: Revert to previous commit
      shell: |
        cd {{ deploy_path }}
        git reset --hard HEAD~1
      register: rollback_result

    - name: Restart containers after rollback
      shell: |
        cd {{ deploy_path }}
        HOST_PROJECT_DIR=$(pwd) docker compose --env-file .env -f {{ compose_file }} up --build -d
