name: Auto Deploy to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CONTABO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.CONTABO_IP }} >> ~/.ssh/known_hosts

      - name: Pull latest code on Contabo
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ secrets.CONTABO_IP }} "
            set -e

            echo '--- Checking Node.js ---'
            if ! command -v node >/dev/null 2>&1; then
              echo 'Node.js not found, installing...'
              apt update -y
              apt install -y nodejs npm
            else
              echo 'Node.js already installed.'
            fi

            echo '--- Checking Docker ---'
            if ! command -v docker >/dev/null 2>&1; then
              echo 'Docker not found, installing...'
              apt update -y
              apt install -y docker-ce docker-ce-cli containerd.io
              systemctl enable docker
              systemctl start docker
            else
              echo 'Docker already installed.'
            fi

            echo '--- Pulling latest code ---'
            cd /www/wwwroot/n8n.atharvadevasthali.com &&
            git fetch origin main &&
            git reset --hard origin/main

            echo '--- Installing dependencies ---'
            npm install > /dev/null 2>&1 &

            echo '--- Running production build ---'
            npm run docker:prod > /dev/null 2>&1 &

            echo '✅ Deployment complete!'
          "
