name: Build & Push Wrapper Service

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Install npm dependencies (only if you have local n8n nodes)
      - name: Install npm dependencies
        if: file-exists('package.json')
        run: npm ci

      # 5. Build n8n nodes (optional)
      - name: Build n8n nodes
        if: file-exists('package.json')
        run: npm run build-n8n-nodes

      # 6. Build the wrapper Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      # 7. Push the image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
